language: python
python:
  - "3.6"
  - "3.9"

script:
  - make deps

dist: bionic

notifications:
  email:
    recipients:
      - developers@growthintel.com
    on_success: never
    on_failure: change

    slack:
      rooms:
        secure: "O/kZr/L3H3R7ndC9aR8ScpL0lN893g8TAsiPdTxVQK7fJ9t88gAonR+yQIq/ZwD4Xwb5NDc09xMBpikhCrquBCqpSxf/EC9tDzePbjlqYCjsZ8wuOmo4byFrH32bvcxr3SIWw8zSY88Z4Ac5msTgUBW2aovOgn9wIM2Prs9kP9y/ftPnlkAs9IJHLJ5DmwEw9KEUTq1eKbWh7+nlguDkBIwpqeuU4gOUAZGFuCy4Cqs53K87PQRX0VjTxnkqODKoF8cuIN9TU0D0u75kqny902rXfzgaSyy8mFFxu+HkPhDbdFICV3H8P82QSpbmUTzcgvfHOBDxZHFJ2cxAScKoLtSzaaHvHA6H3WrHP6r5jei0UgG4v5dNRtyA5uO+DtVu0thr/cpBI97Hm9Ob9sTOCzIRtTuSPyk+cAYsksDDzL67diJhkaaCcIQBL6Z5qSEZzJS+Ggdzo5SwiTDrK/qOW/xk/53qQrB2lL9oQT4vuiTpwSUJnaWDeVlfYk09JnfYWfSHzNWXy+F8aQQylMzuoKGDTtVDya7dpObwCFatJ1yvr1sGu067Y5+04a5fk6hRmPaQDFNEfkN14BF8xw4EQJA2M8Gna6U6bQmkwHRPFIcJpC6vmA6UV5Wvg8Rpgme7GN3R9i07/1+520CeWdYCXFlYWlFy6kpAhECDMO3uJwU="
