name: Unit tests

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda env update --file environment.yml --name base
    - name: Test with pytest
      run: |
        conda config --add channels conda-forge
        conda install scikit-learn=1.0.2 pandas=1.3.5 numpy=1.21.4 scipy=1.7.3  -y -q
        conda install tensorflow joblib pytest -y -q
        conda install imageio scikit-image -y -q
        conda install dlib -y -q
        pip install markdown
        pip install -e  .
        python -c "import numpy; print('NumPy:', numpy.__version__)"
        python -c "import scipy; print('SciPy:', scipy.__version__)"
        python -c "import sklearn; print('Scikit-learn:', sklearn.__version__)"
        python -c "import pandas; print('Pandas:', pandas.__version__)"
        pytest -sv
